package component;

public enum ComponentType {
	INVALID,
	RENDER,
	CONTROLLER,
	PHYSICS,
	GRAVITATION,
	COLLISION,
	COLLISION_LEFT_WALL,
	COLLISION_RIGHT_WALL,
	COLLISION_FLOOR,
	COLLISION_ROOF,
	COLLISION_ACTION,
	DOWNWARD_ACCELERATION;
}
